### ISSUE TITLE
ExitPre sound file gets truncated

### ISSUE THREAD

**Issue by rwmitchell** [lifepillar/vim-keysound#3]
I have a sound file ( female voice saying "All Done!" ) to play on ExitPre.  This worked when using the more basic "call sound_playfile()", but is now getting truncated very quickly after it starts playing.  I'm assuming this is because vim-keysound is much more efficient.

Is there a way to delay the actual exiting until the file is played to end?  Is there a better event to use?

yes, this is a silly use-case.  i'm easily amused.

**Comment by rwmitchell** [comment]
I can no longer recreate my previous implementation that I was convinced worked.

**Comment by rwmitchell** [comment]
Added:

```autocmd VimLeave    * :sleep 1    " allow ExitPre keysound to finish"```

brute force, but it works

**Comment by lifepillar** [comment]
I doubt that this has to do with KeySound.

>This worked when using the more basic "call sound_playfile()"

I have run `vim --clean`,  then executed:

```vim
autocmd ExitPre * call sound_playfile('/path/to/long_sound.wav')
```

and then exited. No sounds was played I guess that it is because the sound is played asynchronously, so Vim does not wait for the sound to be played till the end before exiting. Adding the `sleep` autocomand prevents Vim from existing at once, so I think that it is a proper workaround.

**Comment by rwmitchell** [comment]
I agree with your assessment of the issue.  My memory of it working previously is obviously wrong.
Good to know using sleep is a reasonable solution.
Thanks!
